let waetherIcons = {
    't01d': './img/icons/1-Thunderstorm-with-light-rain.png',
    't01n': './img/icons/1-Thunderstorm-with-light-rain.png',
    't02d': './img/icons/1-Thunderstorm-with-light-rain.png',
    't02n': './img/icons/1-Thunderstorm-with-light-rain.png',
    't03d': './img/icons/2-Thunderstorm-with-heavy-rain.png',
    't03n': './img/icons/2-Thunderstorm-with-heavy-rain.png',
    't04d': './img/icons/1-Thunderstorm-with-light-rain.png',
    't04n': './img/icons/1-Thunderstorm-with-light-rain.png',
    't05d': './img/icons/2-Thunderstorm-with-heavy-rain.png',
    't05n': './img/icons/2-Thunderstorm-with-heavy-rain.png',
    'd01d': './img/icons/3-Light-Drizzle.png',
    'd01n': './img/icons/3-Light-Drizzle.png',
    'd02d': './img/icons/4-Drizzle.png',
    'd02n': './img/icons/4-Drizzle.png',
    'd03d': './img/icons/5-Heavy-Drizzle.png',
    'd03n': './img/icons/5-Heavy-Drizzle.png',
    'r01d': './img/icons/6-Light-Rain.png',
    'r01n': './img/icons/6-Light-Rain.png',
    'r02d': './img/icons/7-Moderate-Rain.png',
    'r02n': './img/icons/7-Moderate-Rain.png',
    'r03d': './img/icons/8-Heavy-Rain.png',
    'r03n': './img/icons/8-Heavy-Rain.png',
    'f01d': './img/icons/9-Freezing-Rain.png',
    'f01n': './img/icons/9-Freezing-Rain.png',
    'r04d': './img/icons/10-Light-Shower-Rain.png',
    'r04n': './img/icons/10-Light-Shower-Rain.png',
    'r05d': './img/icons/10-Light-Shower-Rain.png',
    'r05n': './img/icons/10-Light-Shower-Rain.png',
    'r06d': './img/icons/11-Heavy_Shower_Rain.png',
    'r06n': './img/icons/11-Heavy_Shower_Rain.png',
    's01d': './img/icons/12-Light_Snow.png',
    's01n': './img/icons/12-Light_Snow.png',
    's02d': './img/icons/12-Light_Snow.png',
    's02n': './img/icons/12-Light_Snow.png',
    's03d': './img/icons/13-Heavy-Snow.png',
    's03n': './img/icons/13-Heavy-Snow.png',
    's04d': './img/icons/14-Mix-Snow-Rain.png',
    's04n': './img/icons/14-Mix-Snow-Rain.png',
    's05d': './img/icons/15-Sleet-Flurries.png',
    's05n': './img/icons/15-Sleet-Flurries.png',
    's06d': './img/icons/15-Sleet-Flurries.png',
    's06n': './img/icons/15-Sleet-Flurries.png',
    'a01d': './img/icons/16-Mist-Smoke=Haze.png',
    'a01n': './img/icons/16-Mist-Smoke=Haze.png',
    'a02d': './img/icons/22-Sand.png',
    'a02n': './img/icons/22-Sand.png',
    'a03d': './img/icons/16-Mist-Smoke=Haze.png',
    'a03n': './img/icons/16-Mist-Smoke=Haze.png',
    'a04d': './img/icons/22-Sand.png',
    'a04n': './img/icons/22-Sand.png',
    'a05d': './img/icons/16-Mist-Smoke=Haze.png',
    'a05n': './img/icons/16-Mist-Smoke=Haze.png',
    'a06d': './img/icons/17-Freezing-Fog.png',
    'a06n': './img/icons/17-Freezing-Fog.png',
    'c01d': './img/icons/18-Clear-Sk.png',
    'c01n': './img/icons/18-Clear-Sk.png',
    'c02d': './img/icons/19Few-Clouds.png',
    'c02n': './img/icons/19Few-Clouds.png',
    'c03d': './img/icons/20-Broken-Clouds.png',
    'c03n': './img/icons/20-Broken-Clouds.png',
    'c04d': './img/icons/21-Overcast-Cloud.png',
    'c04n': './img/icons/21-Overcast-Cloud.png',


}
const countryTranslations = {
  // ایران و همسایه‌ها
  "IR": "ایران",
  "AF": "افغانستان",
  "PK": "پاکستان",
  "IQ": "عراق",
  "TR": "ترکیه",
  "TM": "ترکمنستان",
  "AZ": "جمهوری آذربایجان",
  "AM": "ارمنستان",
  "SA": "عربستان سعودی",
  "AE": "امارات متحده عربی",
  "OM": "عمان",
  "QA": "قطر",
  "KW": "کویت",
  "BH": "بحرین",
  "SY": "سوریه",
  "JO": "اردن",
  "LB": "لبنان",
  "YE": "یمن",

  // آسیا
  "CN": "چین",
  "JP": "ژاپن",
  "KR": "کره جنوبی",
  "KP": "کره شمالی",
  "IN": "هند",
  "BD": "بنگلادش",
  "LK": "سریلانکا",
  "TH": "تایلند",
  "MY": "مالزی",
  "SG": "سنگاپور",
  "ID": "اندونزی",

  // اروپا
  "RU": "روسیه",
  "DE": "آلمان",
  "FR": "فرانسه",
  "GB": "بریتانیا",
  "IT": "ایتالیا",
  "ES": "اسپانیا",
  "NL": "هلند",
  "CH": "سوئیس",
  "SE": "سوئد",
  "NO": "نروژ",
  "FI": "فنلاند",
  "PL": "لهستان",
  "UA": "اوکراین",
  "GR": "یونان",

  // آمریکا
  "US": "ایالات متحده آمریکا",
  "CA": "کانادا",
  "MX": "مکزیک",
  "BR": "برزیل",
  "AR": "آرژانتین",

  // آفریقا
  "EG": "مصر",
  "ZA": "آفریقای جنوبی",
  "MA": "مراکش",
  "NG": "نیجریه",

  // اقیانوسیه
  "AU": "استرالیا",
  "NZ": "نیوزیلند"
};

const weatherTranslations = {
  "Thunderstorm with light rain": "رعد و برق با باران سبک",
  "Thunderstorm with rain": "رعد و برق با باران",
  "Thunderstorm with heavy rain": "رعد و برق با باران شدید",
  "Thunderstorm with light drizzle": "رعد و برق با باران ریز سبک",
  "Thunderstorm with drizzle": "رعد و برق با باران ریز",
  "Thunderstorm with heavy drizzle": "رعد و برق با باران ریز شدید",
  "Thunderstorm with hail": "رعد و برق با تگرگ",
  "Light drizzle": "باران ریز سبک",
  "Drizzle": "باران ریز",
  "Heavy drizzle": "باران ریز شدید",
  "Light rain": "باران سبک",
  "Moderate rain": "باران متوسط",
  "Heavy rain": "باران شدید",
  "Freezing rain": "باران یخ‌زده",
  "Light shower rain": "رگبار باران سبک",
  "Shower rain": "رگبار باران",
  "Heavy shower rain": "رگبار باران شدید",
  "Light snow": "برف سبک",
  "Snow": "برف",
  "Heavy snow": "برف شدید",
  "Mix snow/rain": "برف و باران مختلط",
  "Sleet": "باران یخ‌زده / یخبندان",
  "Heavy sleet": "باران یخ‌زده شدید",
  "Snow shower": "رگبار برف",
  "Heavy snow shower": "رگبار برف شدید",
  "Flurries": "بارش پراکنده",
  "Mist": "غبار",
  "Smoke": "دود",
  "Haze": "غبارآلود",
  "Sand/dust": "گرد و غبار / شن",
  "Fog": "مه",
  "Freezing fog": "مه یخ‌زده",
  "Clear Sky": "آسمان صاف",
  "Few clouds": "کمی ابری",
  "Scattered clouds": "ابرهای پراکنده",
  "Broken clouds": "ابرهای پاره‌پاره",
  "Overcast clouds": "آسمان پوشیده از ابر",
  "Unknown precipitation": "بارش نامشخص"
};


export { waetherIcons , countryTranslations , weatherTranslations}